const ACTION_TYPE = {
  SUBMIT_DRAFT_REQUESTED: 'SUBMIT_DRAFT_REQUESTED',
  SUBMIT_DRAFT_SUCCESS: 'SUBMIT_DRAFT_SUCCESS',
  SUBMIT_DRAFT_FAILURE: 'SUBMIT_DRAFT_FAILURE',

  GET_DRAFT_REQUESTED: 'GET_DRAFT_REQUESTED',
  GET_DRAFT_SUCCESS: 'GET_DRAFT_SUCCESS',
  GET_DRAFT_FAILURE: 'GET_DRAFT_FAILURE',

  SAVE_DRAFT_REQUESTED: 'SAVE_DRAFT_REQUESTED',
  SAVE_DRAFT_SUCCESS: 'SAVE_DRAFT_SUCCESS',
  SAVE_DRAFT_FAILURE: 'SAVE_DRAFT_FAILURE',

  EDIT_POST_REQUESTED: 'EDIT_POST_REQUESTED',
  EDIT_POST_SUCCESS: 'EDIT_POST_SUCCESS',
  EDIT_POST_FAILURE: 'EDIT_POST_FAILURE',

  UPLOAD_PHOTO_REQUESTED: 'UPLOAD_PHOTO_REQUESTED',
  UPLOAD_PHOTO_SUCCESS: 'UPLOAD_PHOTO_SUCCESS',
  UPLOAD_PHOTO_FAILURE: 'UPLOAD_PHOTO_FAILURE',

  PUBLISH_POST_REQUESTED: 'PUBLISH_POST_REQUESTED',
  PUBLISH_POST_SUCCESS: 'PUBLISH_POST_SUCCESS',
  PUBLISH_POST_FAILURE: 'PUBLISH_POST_FAILURE',

  SEEN_SUBMIT_TUTORIAL_REQUESTED: 'SEEN_SUBMIT_TUTORIAL_REQUESTED',
  SEEN_SUBMIT_TUTORIAL_SUCCESS: 'SEEN_SUBMIT_TUTORIAL_SUCCESS',
  SEEN_SUBMIT_TUTORIAL_FAILURE: 'SEEN_SUBMIT_TUTORIAL_FAILURE'
};

export default ACTION_TYPE;
